apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-devops-app
  labels:
    app: nextjs-devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-devops-app
  template:
    metadata:
      labels:
        app: nextjs-devops-app
    spec:
      containers:
      - name: nextjs-devops-app
        image: ghcr.io/yourusername/nextjs-devops-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always