apiVersion: v1
kind: Service
metadata:
  name: nextjs-devops-app-service
  labels:
    app: nextjs-devops-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nextjs-devops-app
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-devops-app-nodeport
  labels:
    app: nextjs-devops-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: nextjs-devops-app